version: '3.9'

services:
  master:
    image: hadoop_alpine
    hostname: master
    networks:
      - swarm-net
    environment:
      - REPLICAS=2
      - PASSWORD=master_passwd
      - MASTER_HOSTNAME=master
      - ISMASTER=true
      - SLAVE_HADOOP_PASSWORD=1234

  slaves:
    image: hadoop_alpine
    environment:
      - MASTER_HADOOP_PASSWORD=master_passwd
      - MASTER_HOSTNAME=master
      - REPLICAS=2
      - PASSWORD=1234
    depends_on:
      - master
    deploy:
      replicas: 2
    networks:
      - swarm-net

networks:
  swarm-net:
    name: swarm-net
    external: true
