version: '3.9'

services:
  master:
    image: hadoop_alpine
    hostname: master
    networks:
      - swarm-net
    environment:
      - REPLICAS=3

  slaves:
    image: hadoop_alpine
    environment:
      - MASTER_HADOOP_PASSWORD=1234
      - MASTER_HOSTNAME=master
      - REPLICAS=3
    depends_on:
      - master
    deploy:
      replicas: 3
    networks:
      - swarm-net

networks:
  swarm-net:
    name: swarm-net
    external: true
